//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasureroWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class basurero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public basurero()
        {
            this.detalleestado = new HashSet<detalleestado>();
            this.detalleubicacion = new HashSet<detalleubicacion>();
            this.detalleusuariobasurero = new HashSet<detalleusuariobasurero>();
        }
    
        public int idbasurero { get; set; }
        public string nombreBasurero { get; set; }
        public Nullable<int> capacidad { get; set; }
        public Nullable<int> carga { get; set; }
        public Nullable<System.DateTime> fechaEntradaBasurero { get; set; }
        public Nullable<System.DateTime> fechaSalidaBasurero { get; set; }
        public int fk_bodega { get; set; }
    
        public virtual bodega bodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleestado> detalleestado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleubicacion> detalleubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleusuariobasurero> detalleusuariobasurero { get; set; }
    }
}
