//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasureroWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class basurero
    {
        public int id { get; set; }
        public string nombreBasurero { get; set; }
        public string capacidad { get; set; }
        public Nullable<System.DateTime> fechaEntrada { get; set; }
        public string area { get; set; }
        public string carga { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public int fk_area { get; set; }
        public int fk_estado { get; set; }
    }
}
