//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasureroWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleubicacion
    {
        public int iddetalleUbicacion { get; set; }
        public string direccionDU { get; set; }
        public string longitudDU { get; set; }
        public string latitudDU { get; set; }
        public System.DateTime fechaDU { get; set; }
        public Nullable<int> capacidadDU { get; set; }
        public Nullable<int> cargaDU { get; set; }
        public int fk_ubicacion { get; set; }
        public int fk_tbasurero { get; set; }
    
        public virtual basurero basurero { get; set; }
        public virtual ubicacion ubicacion { get; set; }
    }
}
