//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasureroWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleubicacion
    {
        public int iddetalleUbicacion { get; set; }
        public string detalleLongitudUbicacion { get; set; }
        public string detalleLatitudUbicacion { get; set; }
        public string detalleDireccionUbicacion { get; set; }
        public Nullable<System.DateTime> detalleFecha { get; set; }
        public string detalleCapacidad { get; set; }
        public int fk_ubicacion { get; set; }
        public int fk_basurero { get; set; }
    }
}
