//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasureroWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleestado
    {
        public int iddetalleEstado { get; set; }
        public Nullable<System.DateTime> fechaDetalleEstado { get; set; }
        public string estadoDetalleEstado { get; set; }
        public string capacidadDetalleEstado { get; set; }
        public string areaDetalleEstado { get; set; }
        public int fk_idBasurero { get; set; }
        public int fk_estadoBasurero { get; set; }
    }
}
