//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasureroWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleusuariobasurero
    {
        public int iddetalleUsuarioBasurero { get; set; }
        public string nombreDUB { get; set; }
        public Nullable<int> capacidadDUB { get; set; }
        public Nullable<System.DateTime> fechaEntradaDUB { get; set; }
        public Nullable<System.DateTime> fechaSalidaDUB { get; set; }
        public string areaDUB { get; set; }
        public string direccionDUB { get; set; }
        public int fk_usuario { get; set; }
        public int fk_basurero { get; set; }
    
        public virtual basurero basurero { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
